server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:LightBoard-Alpha.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      pool-name: LightBoardHikari
  jpa:
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect

  thymeleaf:
    enabled: false
    mode: HTML
    # 是否缓存模板（开发环境通常关闭）
    cache: false
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html